image: thinkcompany/docker-node-chrome:latest

pipelines:
  pull-requests:
    '**':
      - step:
          script:
            - npm ci
            - npm run vistest:ci
          caches:
            - node
          artifacts:
            - src/__image_snapshots__/__diff_output__/*.png
            - .npm/**/*.log
